### ISSUE TITLE
where is the paper link ?

### ISSUE THREAD

**Issue by zhuqiang00099** [AVAuco/ssd_people#1]
Hi, could you provide the paper link ? I can not find the paper...

**Comment by zacr0** [comment]
Hello @zhuqiang00099, here is the cited paper's [landing site](http://www.robots.ox.ac.uk/~vgg/research/laeonet/), and [this](http://www.robots.ox.ac.uk/~vgg/research/laeonet/cvpr2019LAEO.pdf) is a direct link to the paper in PDF format.

Thanks for your interest in our work.

**Comment by zhuqiang00099** [comment]
@zacr0 got it,thank you.
